<?php
require 'vendor/autoload.php';
include 'db.php';

use Dompdf\Dompdf;

$dompdf = new Dompdf();

/* ================= GET DATA ================= */
$result = $conn->query("SELECT * FROM sales");

if(!$result){
    die("Database Error: " . $conn->error);
}

/* ================= CALCULATE TOTAL ================= */
$totalRevenue = 0;
$rows = "";

while($row = $result->fetch_assoc()){
    $totalRevenue += $row['total_price'];

    $rows .= "
    <tr>
        <td>{$row['product_name']}</td>
        <td>{$row['market_name']}</td>
        <td>{$row['quantity']}</td>
        <td>GHS {$row['total_price']}</td>
        <td>{$row['sale_date']}</td>
    </tr>
    ";
}

/* ================= HTML DESIGN ================= */
$html = "
<style>
body {
    font-family: Arial, sans-serif;
}

.header {
    text-align: center;
    margin-bottom: 20px;
}

.title {
    font-size: 22px;
    font-weight: bold;
}

.subtitle {
    font-size: 14px;
    color: gray;
}

table {
    width: 100%;
    border-collapse: collapse;
}

th {
    background-color: #28a745;
    color: white;
    padding: 8px;
}

td {
    padding: 8px;
    border: 1px solid #ddd;
}

.summary {
    margin-top: 20px;
    font-size: 16px;
}

.footer {
    margin-top: 30px;
    font-size: 12px;
    text-align: center;
    color: gray;
}
</style>

<div class='header'>
    <div class='title'><i class='fas fa-wheat-awn'></i> Agricultural Market System</div>
    <div class='subtitle'>Sales Report</div>
    <div class='subtitle'>Generated on: ".date("Y-m-d H:i:s")."</div>
</div>

<table>
<tr>
<th>Product</th>
<th>Market</th>
<th>Quantity</th>
<th>Total (GHS)</th>
<th>Date</th>
</tr>

$rows

</table>

<div class='summary'>
<strong>Total Revenue: GHS $totalRevenue</strong>
</div>

<div class='footer'>
Generated by Agricultural Information System
</div>
";

/* ================= GENERATE PDF ================= */
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();

/* ================= DOWNLOAD ================= */
$dompdf->stream("Sales_Report.pdf", ["Attachment" => true]);
?>